Demog schemes placeholders
AfricasVoices/Project-WUSC-KEEP-II pull request #6
Opened 2019-12-03 10:56 UTC by IsaackMwenda

2019-12-04 11:38 UTC, as2388 requested changes

2019-12-04 11:38 UTC, as2388 commented on code_schemes/age.json
> +  "Version": "0.0.0.3",
(0.0.0.4 would sync with the upcoming standards https://github.com/AfricasVoices/Standards/pull/10/files)

2019-12-04 11:38 UTC, as2388 commented on code_schemes/dadaab_hh_language.json
> +  "Name": "Dadaab hh language",
Can we call this 'household' from now on. We abbreviated to 'hh' in the past, but that was confusing and unnecessary.

2019-12-04 11:38 UTC, as2388 commented on code_schemes/dadaab_location.json
> +      "MetaCode": "similar_content",
thanks for remembering these :)

2019-12-04 13:21 UTC, IsaackMwenda commented on code_schemes/age.json
> +  "Version": "0.0.0.3",
updated thanks

2019-12-04 13:22 UTC, IsaackMwenda commented on code_schemes/dadaab_hh_language.json
> +  "Name": "Dadaab hh language",
Updated on both scheme and file. Will update pipeline configurations and code_schemes in a separate pr.

2019-12-04 13:22 UTC, IsaackMwenda commented on code_schemes/dadaab_location.json
> +      "MetaCode": "similar_content",
: )

2019-12-09 11:37 UTC, as2388 approved these changes

2019-12-09 11:38 UTC, as2388 commented
Requesting review from @lukechurch because some of these schemes are new, and to confirm that we should maintain a household language scheme for each location.

2019-12-09 20:57 UTC, lukechurch commented
@IsaackMwenda - I'm a bit nervous about the nationality code - could you send me a pointer to the research design for it?

2019-12-16 22:18 UTC, lukechurch approved these changes

2019-12-17 11:20 UTC, merged